version: '3.8'

services:
  mosquitto_broker:
    image: ubuntu:latest
    container_name: mosquitto_broker
    command: >
      /bin/sh -c "apt-get update && apt-get install -y mosquitto mosquitto-clients nano openssl iproute2 iputils-ping && mosquitto -c /etc/mosquitto/mosquitto.conf"
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./broker-config:/etc/mosquitto
    networks:
      app_network:
        ipv4_address: 172.27.0.2
    restart: unless-stopped

  mosquitto_client:
    image: ubuntu:latest
    container_name: mosquitto_client
    command: >
      /bin/sh -c "apt-get update && apt-get install -y mosquitto-clients nano iproute2 iputils-ping && tail -f /dev/null"
    networks:
      app_network:
        ipv4_address: 172.27.0.3
    restart: unless-stopped

networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24


